### ISSUE TITLE
Implement pretty printing for V2 results

### ISSUE THREAD

**Issue by vilterp** [RelationalAI/rai-sdk-go#15]
They should implement `Showable` like V1 results did, so the CLI can call them here: https://github.com/RelationalAI/rai-cli/blob/a5056e3304760918f5be814ea2b898ba1e2c93ba/rai/cmds.go#L167

cc @NRHelmi. I guess we can copy what we did in the Julia SDK?

**Comment by NHDaly** [comment]
@NRHelmi: We ran into this on the CLI while you were gone. We want to upgrade the CLI to `v2`, but we can't do that yet until we have pretty-printing for the v2 results.

Could you implement this? It should be very similar to what we did in the Julia SDK here:
https://github.com/RelationalAI/rai-sdk-julia/pull/41

**Comment by NHDaly** [comment]
Fixed by https://github.com/RelationalAI/rai-sdk-go/pull/21

**Comment by NHDaly** [comment]
Actually, @NRHelmi can you confirm that #21 is enough to also mark the results as `Showable`, so that they can be pretty-printed from the CLI?

Can you also wrap up the last pieces of work to fix https://github.com/RelationalAI/rai-cli/issues/16? I think they are:
1. Make sure that the results are now `Rai.Showable`
2. Update the CHANGELOG to match the tagged version numbers.
3. Tag a new version of the SDK that now has pretty-printing of results.
4. Update the CLI to use the latest version (with `./tidy`, i think?)
5. Test @vilterp's PR https://github.com/RelationalAI/rai-cli/pull/17, to make sure results look okay on v2.
6. Merge PR https://github.com/RelationalAI/rai-cli/pull/17.

🙏 I would super appreciate it if you can follow that through! :) Thanks in advance!

**Comment by NHDaly** [comment]
Thank you for addressing all of the above! :)

**Comment by billscheidel-rai** [comment]
**Note:** This issue has been migrated to [https://relationalai.atlassian.net/browse/RAI-6082](https://relationalai.atlassian.net/browse/RAI-6082).

_This link is only accessible to employees of RelationalAI._
